name: CD
on:
  release:
    types: [published]

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup UV
        run: pip3 install uv==0.4.30

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build
        run: uv build

      - name: Publish
        run: uv publish
        env:
          UV_PUBLISH_USERNAME: __token__
          UV_PUBLISH_PASSWORD: ${{ secrets.PYPI_TOKEN }}

      - name: Upload artifacts for dist
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/*
